export default function showDamedesu() {
  console.log('＿人人人人人人人人人人＿')
  console.log('＞　進捗ダメです！！　＜')
  console.log('￣Y^Y^Y^Y^Y^Y^Y^Y^Y￣')

  console.log('                        _')
  console.log('                      _:~~')
  console.log('                    .::~:~.')
  console.log('                  .:~~:~~:~')
  console.log('                .~:~:~~::~:_')
  console.log('              .~~:~:~:~:~~:~')
  console.log('            .:~~:~:~~:~~:~~:~           `.')
  console.log('          .~:~~:~~:~:~:~::~`           .uM;')
  console.log('        . ~:~:~:~:~~~:~:~`           .JMMMN')
  console.log('      .Mb  :~~:~~:~:~:~`           .JMMMMMM]')
  console.log('    .MMMMc ~:~~:~~::~` ._:~__-... .MMMMMMMMM.')
  console.log('  .MMMMMMN  ::~::~~` ._:~~:~:~:~:..MMMMMMMMMb')
  console.log(' MMMMMMMMMb _~~:~`` _:~~:~~:~~~:~~ (MMMMMMMMMc')
  console.log(' dMMMMMMMMM, ~:~  _:~:~:~:~~:~:~:~_ MMMMMMMMM3')
  console.log(' .MMMMMMMMMb    .:~~:~:~~:~:~:~~:~~ ,MMMMMM"')
  console.log('  (MMMMMMMM@`    ``~~~~:~~:~:~:~~:~_ dMMM"')
  console.log('   HMMMMMB!                ``~~~:::~..MD')
  console.log('   ,MMM#/           ._::~:_-...')
  console.log('    d#^            _:~~~:~~~~:~~~~:~')
  console.log('                  ~:~~:~~:~:~~:~:~')
  console.log('                   ~:~:~:~:~:~:~')
  console.log('                   _~:~~~:~~:~')
  console.log('                    :~:~:~:~`')
  console.log('                    _~~:~~`')
  console.log('                     ~:~`')
  console.log('                      `')
}
